travis:
  secure:
    BINSTAR_TOKEN: tzJ6Grzf6Duta0t2OoJBd3NSGx740ThC5Beoc3SSDnPMuawuUuLHqTOSNNRycB7I0Zjpprr9BiX7CA4sYC60mf9OOpAFbF3lpWXZXUBAykBxOGo2ryhCPyJH9J/AJ0HcJ6kgX1+dYXQFkeJPaBQoSivFelJGa/jVbPuFhmZTWgitqmCQDiFpfEVQcQDvYrOu0kkJqeJjuhCm9lDlvgRB4SWyDdEd0Plw4L2rhbcsfOFIjXoV/eosJtN4xFFXNMnrb1mBiaQRfVbof6NUzqd0b3SPzqN9oZ3TrA1b2uwBFAZ7AaYfRoTYArCTGP7RwcJgofJWlju6p2j/IK0/rv6Z55NGtqVJim7yHJm36y8gqJjnGgp7lX81MyWfa2h8+PEH8avD8MileENAgIOb75BEL3q1CspjRlbYR50w0xVjHiUyPTjRANX7TWrWBsSXWTgIMD3W7EekvKr7zK0iQv9Y4pfVePUldw2JrKQSF9jXcoL1+o4xXziosbia8XoNLb1onzuK0bcn5dbPrrjTe3VkUVvXuWRBGIMV1IHfiET09GUEHh3FXu+Taq8kYHM7FO/NmjE5vaq2ZiNg4nfa6EKEvl1X07LuduMLepLaSScMGxMIGcwuWsknuKxr98T4vzYiOz/zFgqF0JlCznpYmaimRpH3Hw6dHfuSnU65vjz36ac=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
